name: office-macro-signing
run-name: Office Macro Signing
on:
  push:
    branches:
      - main
    paths:
      - 'Office/**.docm'
      - 'Office/**.dotm'
      - 'Office/**.pptm'
      - 'Office/**.potm'
      - 'Office/**.ppsm'
      - 'Office/**.ppam'
      - 'Office/**.xlsm'
      - 'Office/**.xltm'

jobs:
  office-macro-signing:
    name: office-macro-signing
    permissions:
      contents: write
      id-token: write
    runs-on: windows-latest
    steps:
      - name: Azure Login via OIDC
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Install Certificates
        shell: pwsh
        run: .github/scripts/InstallCertificates.ps1 -RootCert '${{ secrets.ROOT_CERT }}'
      - name: Install Prerequisites
        shell: pwsh
        run: .github/scripts/InstallPrerequisites.ps1 -Latest
      - name: Sign Office Macros
        shell: pwsh
        run: .github/scripts/CodeSigning.ps1 -TenantId '${{ secrets.AZURE_TENANT_ID }}' -KeyVaultUrl '${{ vars.CODE_SIGNING_KEYVAULT }}' -CertName '${{ vars.CODE_SIGNING_CERT_NAME }}' -Path 'Office' -FileExtension '.docm','.dotm','.pptm','.potm','.ppsm','.ppam','.xlsm','.xltm'
      - name: Commit changes to GitHub
        run: |
          git config --local user.name "GitHub Actions[bot]"
          git config --local user.email "github-actions@users.noreply.github.com"
          git checkout -b github-actions-office-macro-signing
          git add *
          git commit -m "GitHub Action Office macros signed"
          git push
          gh pr create --title "github-actions-office-macro-signing"
          gh pr merge --auto
