name: office-macro-signing
run-name: Office Macro Signing
on:
  pull_request_review:
    types:
      - submitted
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  office-macro-signing-labeler:
    name: office-macro-signing-labeler
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: office-macro-signing-labeler
        uses: actions/labeler@v6
  
  office-macro-signing:
    name: office-macro-signing
    needs: office-macro-signing-labeler
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    if: contains(github.event.pull_request.labels.*.name, 'office-macros-signing')
    runs-on: windows-latest
    steps:
      - name: Azure Login via OIDC
        uses: azure/login@532459ea530d8321f2fb9bb10d1e0bcf23869a43
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install Certificates
        shell: pwsh
        run: .github/scripts/InstallCertificates.ps1 -RootCert '${{ secrets.ROOT_CERT }}'
      - name: Install Prerequisites
        shell: pwsh
        run: .github/scripts/InstallPrerequisites.ps1 -Latest
      - name: Sign Office Macros
        shell: pwsh
        run: .github/scripts/CodeSigning.ps1 -TenantId '${{ secrets.AZURE_TENANT_ID }}' -KeyVaultUrl '${{ vars.CODE_SIGNING_KEYVAULT }}' -CertName '${{ vars.CODE_SIGNING_CERT_NAME }}' -Path 'Office' -FileExtension '.docm','.dotm','.pptm','.potm','.ppsm','.ppam','.xlsm','.xltm'
      - name: Commit changes to GitHub
        id: commit
        shell: pwsh
        run: |
          git config --local user.name "GitHub Actions[bot]"
          git config --local user.email "github-actions@users.noreply.github.com"
          $branch = "${{ github.event.pull_request.head.ref }}"
          $pr_url = gh pr view $branch --json url -q .url
          "pr_url=$pr_url" >> $env:GITHUB_OUTPUT
          git add *
          git commit -m "GitHub Action Office macros signed"
          git push
      - name: Approve PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: pwsh
        run: |
          $pr_url = '${{ steps.commit.outputs.pr_url }}'
          "$pr_url"
